### ISSUE TITLE
CSS for the code blocks seems to be off

### ISSUE THREAD

**Issue by wayneadams** [QuantConnect/Documentation#499] opened 2021-11-08 05:56 UTC
When I visit the docs/v2 [pages](https://www.quantconnect.com/docs/v2/lean-cli/tutorials/authentication), I see the code blocks have dark font on a dark background.

Ex:
![image](https://user-images.githubusercontent.com/15034841/140691349-a6cb9671-9bb8-426f-89e6-7ebbbc24ab09.png)

**Comment by DerekMelchin** [comment] 2021-11-11 17:41
Hi wayneadams,

We were unable to reproduce this issue. Which browser did this occur on? Are any browser extensions enabled that would affect the font color?

Best,
Derek Melchin

**Comment by DerekMelchin** [comment] 2022-02-10 21:30
Closing the issue since we were not able to reproduce it.

**Closed by DerekMelchin** 2022-02-10 21:30 UTC
