### ISSUE TITLE
Fix Typos in Trading and Orders

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#348] opened 2020-10-09 13:36 UTC
The `OrderResponse` class has `IsSuccess` member and the [docs](https://www.quantconnect.com/docs/algorithm-reference/trading-and-orders) is wrongly using `IsSuccessful` in the code snippets.

```python
# Create Stop Market Order for 1% below current market price.
close = self.Securities["SPY"].Close
stopMarketTicket = self.StopMarketOrder("SPY", 10, close * 0.99)
```
The quantity is positive indicating a buy order for which the stop order price should be higher than the current, which is lower in this case. So we should either use negative quantity or multiply the close by a number greater than 1.

**Comment by DerekMelchin** [comment] 2022-02-10 22:08
Closing because this issue is a duplicate of https://github.com/QuantConnect/Documentation/issues/331

**Closed by DerekMelchin** 2022-02-10 22:08 UTC
